### ISSUE TITLE
GMake2 Roadmap

### ISSUE THREAD

**Issue by 3JoB** [3JoB/gmake2#5]
**v2.5.0:** support deb, rpm packaging

**v2.6.0:** Support using `@import` keyword to import GMakefile

**The roadmap is subject to change at any time.****

**Comment by 3JoB** [comment]
**Tag Example**

CMD
```sh
gmake2 --tags="golang=1.20,pwd=14bh2 32v"
```

GMakefile
```yml
all: |
  @echo {{.golang}}
  @echo {{.pwd}}
```

**Comment by 3JoB** [comment]
**@import Example**

GMakefile.yml
```yml
var:
  message: GMake2!!!

all: |
  @import Droot
  @run Droot.my_name
  @echo {{.Droot.date}}
```

Droot.yml
```yml
var: 
  date: 1936

my_name: |
  @echo My name is GMake2
  @echo {{.main.message}}
```

Only GMakefile files with suffix yml are allowed to be imported.

Spaces are common to each GMakefile.

The namespace of the main GMakefile defaults to `main`, and the namespace of the sub-GMakefile cannot contain variables or command groups that already exist in the main namespace (such as `main`)
